services:
  app:
    env_file:
      - ../.env
    build:
      context: .. # Build context is the project root
      dockerfile: ./docker/Dockerfile # Path to the Dockerfile
    ports:
      - "8001:8000" # Backend port (8001 externally, 8000 inside container)
      - "5173:5173" # Frontend port
    volumes:
      - ../backend:/app/backend # Mount backend for live reloading
      - ../frontend:/app/frontend # Mount frontend for live reloading
      - /app/frontend/node_modules # Exclude node_modules from host mount
    environment:
      PYTHONUNBUFFERED: 1
      VITE_API_URL: http://localhost:8001
